apiVersion: apps/v1
kind: Deployment
metadata:
  name: feishuservice
  labels:
    app: feishuservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: feishuservice
  template:
    metadata:
      name: feishuservice
      labels:
        app: feishuservice
    spec:
      containers:
        - name: feishuservice
          image: feishuservice/feishuservice:52d0967
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: feishuservice
spec:
  selector:
    app: feishuservice
  ports:
    - protocol: TCP
      name: feishuservice
      port: 6666
      targetPort: 9090
      nodePort: 30001
  type: NodePort