server:
  port: 9090
  servlet:
    context-path: /feishuservice
spring:
  profiles:
    active: dev

openai:
  apikey:
    strategy: round-robin #round-robin, least-usage， random， weighted-round-robin

app:
  id: feishuservice
apollo:
  bootstrap:
    enabled: true
    namespaces: application, redis, hefeng, openai, feishu, db
  cluster: default
  access-key:
    secret: ${APOLLO_ACCESS_KEY}